#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.8.1-jdk-11

pipelines:
  default:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn clean install -Denv=dev -DremoteTesting=true -Dbrowser=firefox
            - cd test-results/jbehave/
            - mv view/jbehave-surefire.xml .
            - rm -rf view/META-INF
            - tar -czvf results.tar.gz *
          artifacts:
            - test-results/jbehave/results.tar.gz
            - test-results/jbehave/jbehave-surefire.xml

      - step:
          name: Deploy to Amazon
          deployment: production
          script:
            - tar -xf test-results/jbehave/results.tar.gz
            - pipe: atlassian/aws-s3-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: 'ui-tests-report'
                LOCAL_PATH: 'view/'
                ACL: 'public-read'
                EXTRA_ARGS: '--debug'
      - step:
          name: Verify Tests Results
          script:
            - for file in test-results/jbehave/*; do if [ "$(grep -c '<failure' "${file}")" -gt 0 ]; then exit 1; fi; done